name: CD - Spring Boot Backend

on:
  workflow_run:
    workflows: ["CI - Spring Boot Backend"]
    types:
      - completed

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code (needed for Docker build context)
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Log in to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Build & Push Docker image (latest + SHA tag)
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            anubhav1404/user-backend:latest
            anubhav1404/user-backend:${{ github.sha }}

  k8s-deploy:
    needs: docker-build
    runs-on: self-hosted  # your self-hosted runner with kubectl access

    steps:
      # 1️⃣ Checkout repo (optional if manifests are in same repo)
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2️⃣ Deploy backend to Kubernetes
      - name: Apply Backend Deployment
        run: |
          kubectl set image deployment/backend-deployment \
            backend=anubhav1404/user-backend:${{ github.sha }}
          kubectl rollout status deployment/backend-deployment
