name: CD - Spring Boot Backend

on:
  workflow_run:
    workflows: ["CI - Spring Boot Backend"]   # must match your CI workflow name
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted   # must have kubectl + kubeconfig configured

    steps:
      # Checkout backend repo at the exact commit built in CI
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}

      # Apply Kubernetes manifests
      - name: Apply Kubernetes manifests
        run: |
          sudo -u ubuntu kubectl apply -f kubernetes/



      # Verify rollout of backend deployment
      - name: Verify rollout
        run: |
          sudo -u ubuntu kubectl rollout status deployment/backend-deployment

      # - name: DAST (OWASP ZAP baseline)
      #   uses: zaproxy/action-baseline@v0.12.0
      #   with:
      #     target: https://backend-service.com
      #   continue-on-error: true
