name: CI - Spring Boot Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3️⃣ Linting (Checkstyle)
      - name: Run Linter
        run: ./mvnw checkstyle:check || true

      # 4️⃣ Dependency scan (Trivy)
      - name: Dependency Scan
        uses: aquasecurity/trivy-action@v0.33.1
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      # 5️⃣ Initialize CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      # 6️⃣ Build project for CodeQL analysis (compile classes)
      - name: Build for CodeQL
        run: ./mvnw clean compile

      # 7️⃣ Perform CodeQL analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      # 8️⃣ Run Unit Tests
      - name: Run Unit Tests
        run: ./mvnw test

      # 9️⃣ Docker login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 🔟 Build & push Docker image
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            anubhav1404/user-backend:latest
            anubhav1404/user-backend:${{ github.sha }}
